### ISSUE TITLE
アームを動作させるときに毎度初期姿勢に戻ってしまう

### ISSUE THREAD

**Issue by MibuchiYuta** [open-rdc/orne_or#43]
実ロボットをmove itを用いて動作させた際に毎回アームが初期姿勢に戻った後、目標の姿勢になる。また、初期姿勢に戻る際はかなり速い動きをするため、サーボモータに望ましくない負荷がかかっている恐れがある。

**Comment by yasuohayashibara** [comment]
gazeboでアームを制御するときのrqt_graph
こちらと同様に接続すればおそらく初期姿勢に戻らなくなると思います．

![image](https://github.com/open-rdc/orne_or/assets/5755200/6ee0f81e-7b9c-45a2-bcdb-f68d39e5cb56)

**Comment by yasuohayashibara** [comment]
orne_or_manipulator_driverのloopbackを使用して作成したrqt_graph
/joint_statusがつながっていない．

![image](https://github.com/open-rdc/orne_or/assets/5755200/552e8568-67e8-4d4b-ae8d-2b9d18a017f1)

**Comment by yasuohayashibara** [comment]
loopbackを使用することで，初期位置からスタートすることを再現できた．
こちらでデバッギングする．

[![IMAGE](http://img.youtube.com/vi/WIkXYQeiGks/0.jpg)](https://youtu.be/WIkXYQeiGks)

gazeboを使用すると，現在の位置からスタートする．

[![IMAGE](http://img.youtube.com/vi/8VHe0JRTL-w/0.jpg)](https://youtu.be/8VHe0JRTL-w)

**Comment by yasuohayashibara** [comment]
`/manipulator/joint_states`が常に0になっている．

```
$ rostopic echo /manipulator/joint_states
```

```
header:
  seq: 350
  stamp:
    secs: 1707973282
    nsecs: 564440011
  frame_id: ''
name:
  - sholder_slider
  - l_sholder_pitch_joint
  - l_sholder_roll_joint
  - l_elbow_roll_joint
  - l_wrist_roll_joint
  - l_wrist_pitch_joint
  - l_wrist_yaw_joint
  - l_hand_left_joint
  - l_hand_right_joint
  - r_sholder_pitch_joint
  - r_sholder_roll_joint
  - r_elbow_roll_joint
  - r_wrist_roll_joint
  - r_wrist_pitch_joint
  - r_wrist_yaw_joint
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
velocity: []
effort: []
```

**Comment by yasuohayashibara** [comment]
`rostopic echo /joint_states`は0ではない．

```
header:
  seq: 1721
  stamp:
    secs: 1707973414
    nsecs: 907071992
  frame_id: ''
name:
  - l_elbow_roll_joint
  - l_sholder_pitch_joint
  - l_sholder_roll_joint
  - l_wrist_pitch_joint
  - l_wrist_roll_joint
  - l_wrist_yaw_joint
  - r_elbow_roll_joint
  - r_sholder_pitch_joint
  - r_sholder_roll_joint
  - r_wrist_pitch_joint
  - r_wrist_roll_joint
  - r_wrist_yaw_joint
  - sholder_slider
position: [1.413367628265008, 0.3316125578789226, -1.180017107273366, 0.0003490658503988659, -0.2331759880664424, 0.3316125578789226, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
